### ISSUE TITLE
Aggregate permissions to admin, edit and view

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#1087]
Permissions for KubeArchive are not automatically added for certain "higher roles" such as "admin", "edit" or "view" which are meant as user facing roles. Its a common practice to provide roles that are automatically aggregated to those using labels:

```
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
    rbac.authorization.k8s.io/aggregate-to-view: "true"
```

More information: https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Acceptance Criteria**

* Create ClusterRoles that provide user-facing functionality and aggregate into the standard set of "higher roles".
