### ISSUE TITLE
ApiServerSource created by the operator does not reach the Ready state.

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#126]
There is an issue with the ApiServerSource deployed by the operator. For some reason it doesn't get into the ready state.  From what I can tell, the resources are identical to other resources that work when applied manually.

This is the error I am seeing on the ApiServerSource object:
```
    - lastTransitionTime: "2024-07-03T11:18:53Z"
      message: User system:serviceaccount:test:kubearchive cannot get, list, watch
        resource "eventses" in API group "" in Namespace "test"
      status: "False"
      type: SufficientPermissions
```

**Comment by rh-hemartin** [comment]
The name `eventses` does not look right to me. Looks as it something was trying to pluralize it from "events" to "eventses". I think the `kind` on the KubeArchiveConfig on the test namespace should not have trailing `s`:

```
---
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
  namespace: test
spec:
  resources:
    - apiVersion: v1
      kind: Events <--
```
