### ISSUE TITLE
Operator creates and manages filter `ConfigMap`.

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#221]
Until `ApiServerSource` can be enhanced to support the type of message filtering needed by `KubeArchive`, `KubeArchive` needs another way to let the sink know when the archive or delete a resource.

This can be done by having the operator create and manage a `ConfigMap` that will contain information that the sink can use to determine if a resource should be archived and then optionally deleted.

This `ConfigMap` will be named `filters` and reside in the `kubearchive` (or `KubeArchive` installation) namespace. It will take the following format:
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: filters
  namespace: kubearchive
data:
  _global:
    - archive-when: .spec.kind == 'PipelineRun' and .status.state in ('Aborted, 'Completed', 'Initializing', 'Failed', 'Running')
      delete-when: .spec.kind == 'PipelineRun' and .status.state in ('Aborted, 'Completed', 'Failed')
  gallen:
    - archive-when: .spec.kind == 'CronJob' 
      delete-when: .spec.kind == 'CronJob' and .status.state in ('Completed')
    - archive-when: .spec.kind == 'Job' 
      delete-when: .spec.kind == 'Job' and .status.state in ('Completed', 'Failed')
  
```
In this `ConfigMap`, the `_global` entry lists filtering rules that should be applied to every namespace that `KubeArchive` is monitoring. This is set by the system administrator and cannot be overriden by users.  All other keys are namespace names, and the list under each namespace represents additional filter rule pairs to control archival and deletion for that particular namespace.

For namespace-specific rules, users would modify the `KubeArchiveConfig` resources in their namespace to add the filtering rules to be applied to that namespace. The operator will then update the `ConfigMap` with the latest rules during its reconciliation.

The operator will create and manage this `ConfigMap`. The sink is the consumer of the data in the `ConfigMap`, and uses the data to determine whether or not to archive the resource in the message.

**Comment by skoved** [comment]
I don't think that the ConfigMap needs to have `archive-when`. To me it makes more sense to receive the messages from ApiServerSource and archive them. The `delete-when` stuff I assume could be implemented in the sink with `CEL` since those look like `CEL` expressions

**Comment by ggallen** [comment]
> since those look like CEL expressions.

I'm not forcing CEL. It could be anything. But I think we need to provide an expression and get it evaluated.  I don't see how this works otherwise.

**Comment by ggallen** [comment]
One problem with the above is that a `ConfigMap` only contains name/value pairs.  So the content of each key would have to be a json string representing the filter pairs.

**Comment by skoved** [comment]
> > since those look like CEL expressions.
> 
> I'm not forcing CEL. It could be anything. But I think we need to provide an expression and get it evaluated. I don't see how this works otherwise.

That's fine. We'll see what we can get to work

**Comment by ggallen** [comment]
> I'm a little worried about how expensive (time and to a lesser extent cpu and memory) evaluating a CEL expression is.

I'd be surprised if the evaluation wasn't fast. I believe the expressions have to be compiled before they can be evaluated.  Whenever the `ConfigMap` is mounted or remounted, I suggest you compile all the expressions and cache them. I don't think `KubeArchiveConfig` resources are going to be changing that often.

**Comment by ggallen** [comment]
> Too many database calls could also be solved with batching.

I would not start with batching.  Just make the individual calls.  We can add batching later if it's a problem.

**Comment by rh-hemartin** [comment]
One thing to keep in mind is that we can reduce the evaluations performed from the sink if we go with a schema like this:

```
spec:
  <namespace>:
    <kind>:
      delete-when:
        - expression
        - expression
      archive-when:
        - expression
        - expression
```

Surfacing the kind would theoretically reduce the time that is needed to go through the list. However this only applies if the list is long or the evaluation is the slowest thing happening on the handler.

**Comment by rh-hemartin** [comment]
I think this solution makes sense as the operator monitors the configuration, it also aggregates them for the sink to consume. ConfigMaps are refreshed on changes[1] so we can setup a syscall to get updates[2] or use some library that has a little better interface.

[1]: https://kubernetes.io/docs/tutorials/configuration/updating-configuration-via-a-configmap/
[2]: https://pkg.go.dev/syscall@go1.22.5#InotifyAddWatch

**Comment by ggallen** [comment]
> One thing to keep in mind is that we can reduce the evaluations performed from the sink if we go with a schema like this:
> 
> ```
> spec:
>   <namespace>:
>     <kind>:
>       delete-when:
>         - expression
>         - expression
>       archive-when:
>         - expression
>         - expression
> ```

I don't see a reason for multiple expressions. What advantage does this give you?

I think it would add confusion. Are the expressions `and`ed or `or`ed?  

Remember the `ConfigMap` can't represent the data this way anyway.  It only allows key/value pairs.

**Comment by maruiz93** [comment]
> Remember the `ConfigMap` can't represent the data this way anyway. It only allows key/value pairs.

Isn't the `ConfigMap` that you provide in the description of this issue facing the same problem?
Note that there are nested key/values inside `_global` and `gallen` keys.

If we want to provide nested values to have just one configmap, a possibility could be this one

```yaml
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: filters
  namespace: kubearchive
data:
  _global.PipelineRun.delete: expression OR (expression AND expression)
  _global.PipelineRun.archive: expression
  gallen.CronJob.delete: expression
  gallen.CronJob.archive: expression
  gallen.Job.delete: expression
  gallen.Job.archive: expression
```

Is kind of a mix of @ggallen and @rh-hemartin, I've included the kind as part of the key, and just one expression (not a list) to allow different operators combination (or / and) and be explicit about them.

Other possibility is to have a YAML, if the ConfigMap is going to be mounted as a file, that would make sense too:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: filters
  namespace: kubearchive
data:
  filters.yaml: |
    _global:
      PipelineRun:
        delete: expression OR (expression AND expression)
        archive: expression
    gallen:
      CronJob:
        delete: expression
        archive: expression
      Job:
       delete: expression
       archive: expression
```
