### ISSUE TITLE
Enhance `KubeArchiveConfig` to support filtering.

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#222]
The `KubeArchiveConfig` resources needs to allow users to specify rules for both archival and deletion of resources in its namespace.
```
---
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
spec:
  resources:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      filters:
        - archive-when: .spec.kind == 'PipelineRun' and .status.state in ('Aborted, 'Completed', 'Initializing', 'Failed', 'Running')
          delete-when: .spec.kind == 'PipelineRun' and .status.state in ('Aborted, 'Completed', 'Failed')
```
From this resource, the operator does two things during reconciliation:
1. Configures the local `ApiServerSource` using the `apiVersion` and `kind` fields so messages are sent.
1. Adds the rules to the "filters" `ConfigMap` in the `kubearchive` namespace for this namespace.

Some notes:

- If no filters are specified, nothing is archived or deleted.
- If a filter does not contain a `delete-when` key, no deleting is done.
- The presence of a `delete-when` keys forces an archive of the resource before deletion, regardless of whether or not `archive-when` is specified.

This is closely related to https://github.com/kubearchive/kubearchive/issues/221.
