### ISSUE TITLE
Add tracing to the DEVELOPMENT.md

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#294]
Now we have a telemetry deployment available for us in development, we need to document it.

The process to enable telemetry is:

1. After installing knative eventing, create the following ConfigMap:
    ```
    kubectl apply -f - <<EOF
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: config-tracing
      namespace: knative-eventing
    data:
      backend: "zipkin"
      zipkin-endpoint: "http://traces-collector.kubearchive.svc.cluster.local:9411/api/v2/spans"
      sample-rate: "1"
    EOF
    ```
1. Pass `--set "integrations.observability.enabled=true"` to helm's install command.
1. Port forward the Jaeger port: `kubectl port-forward -n kubearchive svc/traces-collector 16686:16886 &`

After generating traffic in the sink or API we should see traces there. The traces from the sink are wrapped into apiserversource traces, as we receive a POST call and then we react to it.
