### ISSUE TITLE
Add "ArchiveOnDelete" functionality

### ISSUE THREAD

**Issue by ggallen** [kubearchive/kubearchive#337]
It would be useful for KubeArchive to allow users to designate resource to be archived when deleted outside of KubeArchive.

There are other tools out there that handle deleting resources.  Giving users the ability to archive these resource before deletion could prove valuable.

This could easily be done by adding an optional `archiveOnDelete` key to each resource in the `KubeArchiveConfig` resource. It would default to `false`.  If this flag is `true`, then sink should receive the delete message and archive the resource.

The sink needs to differentiate between a delete it initiated and one initiated by another means, and if the sink initiated the delete then the `archiveOnDelete` flag should be ignored. `archiveOnDelete` only applies to delete messages.

The sink would also need to include `archiveOnDelete` in it's CEL expressions.

**Comment by ggallen** [comment]
It might be more powerful to have `archiveOnDelete` take an expression as well, similar to both `archiveWhen` and `deleteWhen`.

**Comment by skoved** [comment]
just want to make sure that we're on the same page. With `archiveOnDelete`, I would be able to have a `KubeArchiveConfig` that looks something like this?

```
---
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
  namespace: ns
spec:
  resources:
    - selector:
        apiVersion: v1
        kind: Event
      archiveWhen: status.state != 'Completed'
      deleteWhen: status.state == 'Completed'
      archiveOnDelete: metadata.labels.version == 'v1.0.0'
```
