### ISSUE TITLE
Document how to configure global filters

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#509]
Hey! There are mention of global filters at #223 , but the linked PR contains no documentation that explain how to configure that. I'm trying to come up with some process for it, but its not being successful. The script I'm using (after installing as per the DEVELOPMENT.md) is:

<details>
<summary>Code to reproduce</summary>

```
set -o errexit
set -o xtrace

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-filters
  namespace: kubearchive
data:
  _global: |
    - selector:
        apiVersion: batch/v1
        kind: CronJob
      archiveWhen: "true"
    - selector:
        apiVersion: batch/v1
        kind: Job
      archiveWhen: has(status.startTime)
      deleteWhen: has(status.completionTime)
    - selector:
        apiVersion: v1
        kind: Pod
      archiveOnDelete: "true"
EOF


cat <<EOF | kubectl apply -f -
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
  namespace: default
spec:
  resources: []
EOF

cat <<EOF | kubectl apply -f -
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: generate
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              args: [date]
          restartPolicy: OnFailure
EOF

```
</details>

This modifies the `_global_` property on the `sink-filters` ConfigMap and then creates an empty KubeArchiveConfig on my target namespace. Is this the right approach?

PD: I got an error while doing this, I'm opening another issue with the error.

Edit: the code in this description is no longer the last version, I added the new version in a comment below.
