### ISSUE TITLE
Error while configuring global filters

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#510]
I'm trying to configure global filters and I'm having an error. Maybe my approach to configure them is wrong, but there are no documentation either. That is a different issue and is being addressed at #509 . To reproduce the problem install as stated in DEVELOPMENT.md and run:

```
set -o errexit
set -o xtrace

cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-filters
  namespace: kubearchive
data:
  _global: |
    - selector:
        apiVersion: batch/v1
        kind: CronJob
      archiveWhen: "true"
    - selector:
        apiVersion: batch/v1
        kind: Job
      archiveWhen: has(status.startTime)
      deleteWhen: has(status.completionTime)
    - selector:
        apiVersion: v1
        kind: Pod
      archiveOnDelete: "true"
EOF


cat <<EOF | kubectl apply -f -
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
  namespace: default
spec:
  resources: []
EOF

cat <<EOF | kubectl apply -f -
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: generate
              image: busybox:latest
              imagePullPolicy: IfNotPresent
              args: [date]
          restartPolicy: OnFailure
EOF
```

Then get the events and the log for the API Server Source pod. In my case:

```
$ kubectl logs -n kubearchive apiserversource-kubearchive-a13e2ebe60ef8d1bf5c1cadfb82d73wknw2
2024/10/07 15:00:24 failed to register opencensus views, event_count: cannot register view "event_count"; a different view with the same name is already registered
{"level":"info","ts":"2024-10-07T15:00:24.592Z","caller":"v2/main.go:329","msg":"Registering 4 clients","commit":"c3baeda"}
{"level":"info","ts":"2024-10-07T15:00:24.592Z","caller":"v2/main.go:330","msg":"Registering 3 informer factories","commit":"c3baeda"}
{"level":"info","ts":"2024-10-07T15:00:24.592Z","caller":"v2/main.go:331","msg":"Registering 2 informers","commit":"c3baeda"}
{"level":"info","ts":"2024-10-07T15:00:24.592Z","caller":"v2/main.go:332","msg":"Registering 2 ducks","commit":"c3baeda"}
{"level":"warn","ts":"2024-10-07T15:00:24.593Z","caller":"v2/config.go:221","msg":"Sink timeout configuration is invalid, default to -1 (no timeout)","commit":"c3baeda"}
{"level":"info","ts":"2024-10-07T15:00:24.593Z","caller":"apiserver/adapter.go:89","msg":"STARTING -- apiserver.Config{Namespaces:[]string{}, AllNamespaces:false, Resources:[]apiserver.ResourceWatch{apiserver.ResourceWatch{GVR:schema.GroupVersionResource{Group:\"\", Version:\"\", Resource:\"cronjobs\"}, LabelSelector:\"\"}, apiserver.ResourceWatch{GVR:schema.GroupVersionResource{Group:\"\", Version:\"\", Resource:\"jobs\"}, LabelSelector:\"\"}, apiserver.ResourceWatch{GVR:schema.GroupVersionResource{Group:\"\", Version:\"\", Resource:\"pods\"}, LabelSelector:\"\"}}, ResourceOwner:(*v1.APIVersionKind)(nil), EventMode:\"Resource\", Filters:[]v1.SubscriptionsAPIFilter(nil)}","commit":"c3baeda"}
{"level":"fatal","ts":"2024-10-07T15:00:24.593Z","caller":"v2/main.go:311","msg":"Start returned an error","commit":"c3baeda","error":"failed to retrieve information about resource /, Resource=cronjobs: groupVersion shouldn't be empty","stacktrace":"knative.dev/eventing/pkg/adapter/v2.MainWithInformers\n\tknative.dev/eventing/pkg/adapter/v2/main.go:311\nknative.dev/eventing/pkg/adapter/v2.MainWithEnv\n\tknative.dev/eventing/pkg/adapter/v2/main.go:163\nknative.dev/eventing/pkg/adapter/v2.MainWithContext\n\tknative.dev/eventing/pkg/adapter/v2/main.go:138\nmain.main\n\tknative.dev/eventing/cmd/apiserver_receive_adapter/main.go:42\nruntime.main\n\truntime/proc.go:271"}
```

The API Server Source definition looks wrong (removed not interesting parts):

```
$ kubectl get -n kubearchive apiserversources.sources.knative.dev kubearchive-a13e -o yaml
apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  creationTimestamp: "2024-10-07T14:59:38Z"
  finalizers:
  - apiserversources.sources.knative.dev
  generation: 1
  name: kubearchive-a13e
  namespace: kubearchive
  ...........
spec:
  mode: Resource
  namespaceSelector:
    matchLabels:
      kubearchive.org/enabled: "true"
  resources:
  - apiVersion: ""
    kind: CronJob
  - apiVersion: ""
    kind: Job
  - apiVersion: ""
    kind: Pod
  serviceAccountName: kubearchive-a13e
  sink: ......................
status:
    ..........
  - lastTransitionTime: "2024-10-07T14:59:38Z"
    message: User system:serviceaccount:kubearchive:kubearchive-a13e cannot get, list,
      watch resource "cronjobs" in API group "" in Namespace "default", get, list,
      watch resource "jobs" in API group "" in Namespace "default"
    status: "False"
    type: Ready
    .............
  - lastTransitionTime: "2024-10-07T14:59:38Z"
    message: User system:serviceaccount:kubearchive:kubearchive-a13e cannot get, list,
      watch resource "cronjobs" in API group "" in Namespace "default", get, list,
      watch resource "jobs" in API group "" in Namespace "default"
    status: "False"
    type: SufficientPermissions
  namespaces:
  - default
  observedGeneration: 1
  sinkUri: http://kubearchive-sink.kubearchive.svc.cluster.local
```

So the configuration is not properly created. It needs permissions too.
