### ISSUE TITLE
Fix service name on ApiServerSource

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#589]
When KubeArchive creates the ApiServerSource, reacting to a KubeArchiveConfig creation, the service name set as a sink on the ApiServerSource is wrong. KubeArchive assumes the service name starts with the same word as the namespace its running on, so if KubeArchive is installed on `mynamespace` the Service assigned as sink in the ApiServerSource is named `mynamespace-sink`. The sink Service name is independent from the namespace is located at, so its always `kubearchive-sink`.

**Acceptance Criteria**

* The APIServerSource created points to the service called `kubearchive-sink` instead of `<namespace>-sink`.

**Notes**

* While we discussed that KubeArchive should be installed on the namespace `kubearchive` and we agreed, there are some clusters that don't allow namespace that start with `kube` so users are forced to change the namespace where KubeArchive is installed.

**Comment by skoved** [comment]
I'll pick this up since I this also is an issue with the names for brokers as well

**Comment by skoved** [comment]
I think this can be resolved with by adding the following to `charts/kubearchive/template/operator/operator.yaml`:

```
env:
  ...
  - name: KUBEARCHIVE_PREFIX
    value: {{ Release.Name }}
```

Then in `cmd/operator/internal/controller/kubearchiveconfig_controller.go` make the following change
```
var (
    ...
    k9ePrefix = os.Getenv("KUBEARCHIVE_PREFIX")
    k9eSinkName = k9ePrefix + "-sink"
    k9eBrokerName = k9ePrefix + "-broker"
    ...
)
```
As far as I can tell `k9eSinkName` is used as the name for the service account in the code as well so I think this fix will address all these issues

**Comment by ggallen** [comment]
I believe this is already working:
```
          env:
            - name: KUBEARCHIVE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```

**Comment by ggallen** [comment]
Ignore my previous comment. I know understand the problem.

**Comment by skoved** [comment]
so far I had to add this:

```
- patch: |-
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: kubearchive-operator-certificate
      namespace: kubearchive
    spec:
      dnsNames:
        - "kubearchive-operator-webhooks.product-kubearchive.svc"
        - "kubearchive-operator-webhooks.product-kubearchive.svc.cluster.local"
```

but I'm now running into this error when applying a `KubeArchiveConfig`

```
Error from server (InternalError): error when creating "/home/skoved/work/kubearchive/kubearchive/test/log-generators/cronjobs/kaconf.yaml": Internal error occurred: failed calling webhook "mkubearchiveconfig.kb.io": failed to call webhook: Post "https://kubearchive-operator-webhooks.product-kubearchive.svc:443/mutate-kubearchive-kubearchive-org-v1alpha1-kubearchiveconfig?timeout=10s": tls: failed to verify certificate: x509: certificate signed by unknown authority
```
