### ISSUE TITLE
Adjust API REST templates in Helm Chart to the defined naming conventions

### ISSUE THREAD

**Issue by maruiz93** [kubearchive/kubearchive#90]
## Helm Chart Naming Conventions

* The resource name must not contain the `kind` of the resource in the name. For example, the database secret shouldn't be `kubearchive-database-secret` and should be `kubearchive-database` instead.
* The resource names must be fully templated with no hardcoded values.

To prevent having several variables in a name resource like: {{ Release.Name }}-{{ .Values.sink.name }} we will take advantage of the [tpl function](https://helm.sh/docs/howto/charts_tips_and_tricks/#using-the-tpl-function):

```yaml
# values
operator: 
  name: "{{ .Release.Name }}-operator"

# template
{{ tpl .Values.operator.name . }}

# output
kubearchive-operator
```

## Goal

Review and update the Helm Chart templates related to the kubearchive API REST component to comply with the naming conventions.
