### ISSUE TITLE
Add a delay to delete resources

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#906]
Currently we delete immediately a resource when we need to, this caused some problems related with fluentbit, that didn't have enough time to scan resources to fill log metadata causing logs to be sent without Kubernetes metadata. Other systems may want a delayed deletion too, so other systems that depend on the resource can react before the resource gets deleted.

**Acceptance Criteria**
* Introduce a configurable delay for deleting resources.

**Notes**
* Implementation-wise there are many options, some are: create a pool of resources to be deleted and have a timer that executes a function over that pool, wait on the same endpoint that needs to delete the resource, etc.

**Comment by ggallen** [comment]
Note that this should only delay the deletion of the resource.  The CloudEvent should be received, the archive should happen, the delete should be scheduled, and then the successful response should be sent.

**Comment by skoved** [comment]
For setting a delay, we add a `delay` field to `resource` in the `KubeArchiveConfig`. This would get propagated by the operator into the sink-filters `ConfigMap` where the sink would process it along with the filters. The `KubeArchiveConfig` would look something like this

```
---
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
  namespace: ns
spec:
  resources:
    - selector:
        apiVersion: v1
        kind: Event
      archiveWhen: status.state != 'Completed'
      deleteWhen: status.state == 'Completed'
      delay: <delay duration>
```

Then if the delay either is unset (unless we want to set a default delay if the user does not provide one) or it is <= 0, the sink would delete the resource immediately (current behavior) otherwise it would call [`time.AfterFunc`](https://pkg.go.dev/time#Timer) with delay to delete the resource after the specified delay.

I'm not sure if we would need a separate go routine to handle this, since the `*Timer` returned by `time.AfterFunc` calls the function you pass to it on a separate goroutine after the specified duration
