### ISSUE TITLE
Investigate memory consumption with +500 KubeArchiveConfigs

### ISSUE THREAD

**Issue by rh-hemartin** [kubearchive/kubearchive#986]
Currently we are seeing a large amount of memory being consumed by the sink when there are a lot of KubeArchiveConfigs. In the installation we have there are 531 entries in the `sink-filters` ConfigMap and there are global filters. We know for a fact that 530 of those 531 KubeArchive configs are empty, the only populated is the global one.

To reproduce a similar problem locally run:

```
kind create cluster
export KO_DOCKER_REPO="kind.local"
bash hack/quick-install.sh
bash integrations/observability/grafana/install.sh
```

Then apply a global config:

```
---
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
spec:
  resources:
    - selector:
        apiVersion: batch/v1
        kind: CronJob
      archiveWhen: "true"
    - selector:
        apiVersion: batch/v1
        kind: Job
      archiveWhen: has(status.startTime)
      deleteWhen: has(status.completionTime)
    - selector:
        apiVersion: v1
        kind: Pod
      archiveOnDelete: "true"
```

And then:

```
for i in {1..500}; do kubectl create ns test-$i; kubectl apply -f kac.yaml -n test-$i; done
```

Where kac.yaml is:

```
---
apiVersion: kubearchive.kubearchive.org/v1alpha1
kind: KubeArchiveConfig
metadata:
  name: kubearchive
spec:
  resources: []
```

You can retrieve heap dumps to inspect resource usage as well:

```
kubectl port-forward -n kubearchive svc/kubearchive-sink 8080:80  &
go tool pprof -http :8081 -no_browser http://localhost:8080/debug/pprof/heap
# go to localhost:8081
```
